SCREEN_WIDTH = 1250
SCREEN_HEIGHT = 703
TILE_SIZE = 64
SCROLL_THRESH = 100
FPS = 60
TIME_LIMIT = 120000
TIME_LIMIT_SECONDS = TIME_LIMIT // 1000
NUMBER_OF_INFECTED_NPC = 1
NUMBER_OF_HEALTHY_NPC = 1

#animations
ATTACK_COOLDOWN = 60
MOVE_COOLDOWN = 150
IDDLE_COOLDOWN = 150
DEATH_COOLDOWN = 140
NPC_ANIMATION = 100
INFECTED_COEFICIENT = 3
ANIMATION_MIN_TIME = 500
ANIMATION_MAX_TIME = 30000
INTRO_ANIMATION_FRAME_TIME = 3000

#fonts
TIME_TEXT_FONT_SIZE = 36
INTRO_TEXT_FONT_SIZE = 60
TEXT_OUTLINE_THICKNESS = 4
INTRO_SLIDES_TEXT = ['Merciii', 'Gimme', 'Nom Nom', 'Oh no', 'Hero is here to save you']


#collisions
X_SHIFT = 40
WIDTH_SCALE = 80

COUCHE = 1
EAT = 2
HAPPY = 3

#sound cooldown
ANOUC = 200